type = "card"
title = "Teaching"
description = "Since Spring 2025, I have served as a teaching assistant (undergruadate student teaching fellow) every semester, supporting a different undergraduate course each term. Here are the courses I have assisted with."

[[items]]
title = "PHY1001 Mechanics"
subtitle = "USTF"
date = "Spring 2025"
content = "Instructors: Prof. Bowen Xiao, Prof. Han Lin & Prof. Xiaolu Zhuo"
tags = ["Undergraduate", "Physics"]

[[items]]
title = "PHY2610 Mathematical Methods in Physics I"
subtitle = "USTF"
date = "Autumn 2025"
content = "Instructor: Prof. Bowen Xiao"
tags = ["Undergraduate", "Physics"]

[[items]]
title = "PHY3110 Classical Mechanics I"
subtitle = "USTF"
date = "Spring 2026"
content = "Instructor: Prof. Jianhui Zhang"
tags = ["Undergraduate", "Physics"]

[[items]]
title = "PHY3410 Quantum Mechanics and its application I"
subtitle = "USTF"
date = "Autumn 2026"
content = "Instructor: Prof. Bowen Xiao"
tags = ["Undergraduate", "Physics"]
